### ISSUE TITLE
Getting URL Format error from print mgr.is_up() Deep Security as a service

### ISSUE THREAD

**Issue by tamoanxx** [deep-security/deep-security-py#2]
Thanks for taking the time to submit an issue. There's a couple of things that will make this easier for everyone involve. If you could please take the time to complete the list below, it's much appreciated.

- [ ] I'm using Deep Security version Latest

- [ ] I'm using the latest version of this repo. If not, version latest

- [ ] My Deep Security Manager has a self-signed or non-validating SSL certificate

In addition, can you please fill in each of the remaining sections.

## Expected behaviour 
Should return true 
## Actual behaviour
Getting URL format error
## Steps to reproduce the behaviour
Use your readme example

**Comment by marknca** [comment]
@tamoanxx thanks for the report. We're currently investigating and should have an update soon

**Comment by marknca** [comment]
Resolve. As of [5afb368f50ba9fb0bda65837a690e7d8bf416747](https://github.com/deep-security/deep-security-py/commit/5afb368f50ba9fb0bda65837a690e7d8bf416747), function returns ```True or False```
