### ISSUE TITLE
When adding an existing AWS account the response is not handled correctly

### ISSUE THREAD

**Issue by jonen10** [deep-security/deep-security-py#7]
Thanks for taking the time to submit an issue. There's a couple of things that will make this easier for everyone involve. If you could please take the time to complete the list below, it's much appreciated.

- [x] I'm using Deep Security version 9.6.3177

- [x] I'm using the latest version of this repo..

- [x] My Deep Security Manager has a self-signed or non-validating SSL certificate

In addition, can you please fill in each of the remaining sections.

## Expected behaviour 
When attempting to add an AWS account that already exists in the DSM there should be a HTTP 400 response with the body containing an error message stating the account already exists. 

## Actual behaviour
An Exception is caught for the 400 response in core.py _request() so no result data is returned to add_aws_account()

## Steps to reproduce the behaviour
As per readme

```python
import deepsecurity

mgr = deepsecurity.dsm.Manager(hostname='ip', username='user',
                               password='#####', ignore_ssl_validation=True)

mgr.sign_in()

response = mgr.cloud_accounts.add_aws_account(friendly_name, aws_access_key=AWS_ACCESS_KEY,
                                              aws_secret_key=AWS_SECRET_KEY,region='eu-west-1')

mgr.sign_out()
```

**Comment by marknca** [comment]
@jonen10 when you increase the logging level (```mgr.log_at_level = 10```) you can see that the response from the Deep Security is actually a 400. I'll open a bug with the core development team to have it return a more accurate error

Sample return: 
```
[2016-07-16 22:30:06]	Failed to make REST POST call [cloudaccounts] Threw exception:
	HTTP Error 400: Bad Request
[2016-07-16 22:30:06]	Call returned HTTP status None and 0 bytes of data
{'eu-west-1': {'status': None, 'raw': None, 'data': None}}
```

**Comment by jonen10** [comment]
Hi @marknca

The add_aws_account() method is expecting a response returned that contains 'raw' data and a '200' status code if an existing account is added. I don't think this will ever be met as the response from the DSM is being caught as an exception and not a valid response i.e. no response data

```python
if not responses[region_to_add] and responses[region_to_add]['status'] == 200:
        if responses[region_to_add]['raw'] and 'Cloud Account Region/Partition already present' in responses[region_to_add]['raw']:
          self.log("The account/region you request has already been added to Deep Security. A specific account/region combination can only be added once")
```

Should we expect any call to the DSM that would generate an error, of any sort, to return a '400' status? Or are there scenarios were a 200 would be returned with some 'raw' data containing error details?
